// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: logger.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_logger_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_logger_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_logger_proto_rawDescGZIP(), []int{0}
}

type LogRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Level       LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=loggerServer.v1.LogLevel" json:"level,omitempty"`
	Timestamp   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Service     string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	OperationId int32                  `protobuf:"varint,4,opt,name=operationId,proto3" json:"operationId,omitempty"`
	TraceId     string                 `protobuf:"bytes,5,opt,name=traceId,proto3" json:"traceId,omitempty"`
	UserId      string                 `protobuf:"bytes,6,opt,name=userId,proto3" json:"userId,omitempty"`
	Message     string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Method      string                 `protobuf:"bytes,8,opt,name=method,proto3" json:"method,omitempty"`
	Path        string                 `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`
	StatusCode  int32                  `protobuf:"varint,10,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	DurationMS  int64                  `protobuf:"varint,11,opt,name=durationMS,proto3" json:"durationMS,omitempty"`
	EntityType  string                 `protobuf:"bytes,12,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId    string                 `protobuf:"bytes,13,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	// service fields
	StringFields map[string]string `protobuf:"bytes,20,rep,name=stringFields,proto3" json:"stringFields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IntFields    map[string]int64  `protobuf:"bytes,21,rep,name=intFields,proto3" json:"intFields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// error
	ErrorMessage  string `protobuf:"bytes,30,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	StackTrace    string `protobuf:"bytes,31,opt,name=stackTrace,proto3" json:"stackTrace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_logger_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogRequest) GetOperationId() int32 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

func (x *LogRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LogRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LogRequest) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *LogRequest) GetDurationMS() int64 {
	if x != nil {
		return x.DurationMS
	}
	return 0
}

func (x *LogRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *LogRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *LogRequest) GetStringFields() map[string]string {
	if x != nil {
		return x.StringFields
	}
	return nil
}

func (x *LogRequest) GetIntFields() map[string]int64 {
	if x != nil {
		return x.IntFields
	}
	return nil
}

func (x *LogRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *LogRequest) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_logger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_logger_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *LogResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type BatchLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorPos      int64                  `protobuf:"varint,3,opt,name=errorPos,proto3" json:"errorPos,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLogResponse) Reset() {
	*x = BatchLogResponse{}
	mi := &file_logger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLogResponse) ProtoMessage() {}

func (x *BatchLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLogResponse.ProtoReflect.Descriptor instead.
func (*BatchLogResponse) Descriptor() ([]byte, []int) {
	return file_logger_proto_rawDescGZIP(), []int{2}
}

func (x *BatchLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchLogResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *BatchLogResponse) GetErrorPos() int64 {
	if x != nil {
		return x.ErrorPos
	}
	return 0
}

func (x *BatchLogResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_logger_proto protoreflect.FileDescriptor

const file_logger_proto_rawDesc = "" +
	"\n" +
	"\flogger.proto\x12\x0floggerServer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x06\n" +
	"\n" +
	"LogRequest\x12/\n" +
	"\x05level\x18\x01 \x01(\x0e2\x19.loggerServer.v1.LogLevelR\x05level\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12 \n" +
	"\voperationId\x18\x04 \x01(\x05R\voperationId\x12\x18\n" +
	"\atraceId\x18\x05 \x01(\tR\atraceId\x12\x16\n" +
	"\x06userId\x18\x06 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x16\n" +
	"\x06method\x18\b \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\t \x01(\tR\x04path\x12\x1e\n" +
	"\n" +
	"statusCode\x18\n" +
	" \x01(\x05R\n" +
	"statusCode\x12\x1e\n" +
	"\n" +
	"durationMS\x18\v \x01(\x03R\n" +
	"durationMS\x12\x1f\n" +
	"\ventity_type\x18\f \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\r \x01(\tR\bentityId\x12Q\n" +
	"\fstringFields\x18\x14 \x03(\v2-.loggerServer.v1.LogRequest.StringFieldsEntryR\fstringFields\x12H\n" +
	"\tintFields\x18\x15 \x03(\v2*.loggerServer.v1.LogRequest.IntFieldsEntryR\tintFields\x12\"\n" +
	"\ferrorMessage\x18\x1e \x01(\tR\ferrorMessage\x12\x1e\n" +
	"\n" +
	"stackTrace\x18\x1f \x01(\tR\n" +
	"stackTrace\x1a?\n" +
	"\x11StringFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eIntFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"i\n" +
	"\vLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\"\n" +
	"\ferrorMessage\x18\x03 \x01(\tR\ferrorMessage\"\x8a\x01\n" +
	"\x10BatchLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x1a\n" +
	"\berrorPos\x18\x03 \x01(\x03R\berrorPos\x12\"\n" +
	"\ferrorMessage\x18\x04 \x01(\tR\ferrorMessage*w\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x042\x9f\x01\n" +
	"\rLoggerService\x12@\n" +
	"\x03Log\x12\x1b.loggerServer.v1.LogRequest\x1a\x1c.loggerServer.v1.LogResponse\x12L\n" +
	"\bBatchLog\x12\x1b.loggerServer.v1.LogRequest\x1a!.loggerServer.v1.BatchLogResponse(\x01B\x11Z\x0floggerServer/v1b\x06proto3"

var (
	file_logger_proto_rawDescOnce sync.Once
	file_logger_proto_rawDescData []byte
)

func file_logger_proto_rawDescGZIP() []byte {
	file_logger_proto_rawDescOnce.Do(func() {
		file_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logger_proto_rawDesc), len(file_logger_proto_rawDesc)))
	})
	return file_logger_proto_rawDescData
}

var file_logger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_logger_proto_goTypes = []any{
	(LogLevel)(0),                 // 0: loggerServer.v1.LogLevel
	(*LogRequest)(nil),            // 1: loggerServer.v1.LogRequest
	(*LogResponse)(nil),           // 2: loggerServer.v1.LogResponse
	(*BatchLogResponse)(nil),      // 3: loggerServer.v1.BatchLogResponse
	nil,                           // 4: loggerServer.v1.LogRequest.StringFieldsEntry
	nil,                           // 5: loggerServer.v1.LogRequest.IntFieldsEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_logger_proto_depIdxs = []int32{
	0, // 0: loggerServer.v1.LogRequest.level:type_name -> loggerServer.v1.LogLevel
	6, // 1: loggerServer.v1.LogRequest.timestamp:type_name -> google.protobuf.Timestamp
	4, // 2: loggerServer.v1.LogRequest.stringFields:type_name -> loggerServer.v1.LogRequest.StringFieldsEntry
	5, // 3: loggerServer.v1.LogRequest.intFields:type_name -> loggerServer.v1.LogRequest.IntFieldsEntry
	1, // 4: loggerServer.v1.LoggerService.Log:input_type -> loggerServer.v1.LogRequest
	1, // 5: loggerServer.v1.LoggerService.BatchLog:input_type -> loggerServer.v1.LogRequest
	2, // 6: loggerServer.v1.LoggerService.Log:output_type -> loggerServer.v1.LogResponse
	3, // 7: loggerServer.v1.LoggerService.BatchLog:output_type -> loggerServer.v1.BatchLogResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_logger_proto_init() }
func file_logger_proto_init() {
	if File_logger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logger_proto_rawDesc), len(file_logger_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logger_proto_goTypes,
		DependencyIndexes: file_logger_proto_depIdxs,
		EnumInfos:         file_logger_proto_enumTypes,
		MessageInfos:      file_logger_proto_msgTypes,
	}.Build()
	File_logger_proto = out.File
	file_logger_proto_goTypes = nil
	file_logger_proto_depIdxs = nil
}
