// Proctor 模块 protobuf 定义
// 用于 Go Proctor 和 Java API Server 之间的数据交换和 gRPC 通信

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proctor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QuestionItem 试卷中的一道题目（含答案和分值，仅内部使用）。
type QuestionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"` // 题目 ID
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`                               // 题型: 1=单选, 2=是非
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`                             // 分值
	Stem          string                 `protobuf:"bytes,4,opt,name=stem,proto3" json:"stem,omitempty"`                                // 题干
	Options       []string               `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`                          // 选项列表 (是非题可为空)
	Answer        string                 `protobuf:"bytes,6,opt,name=answer,proto3" json:"answer,omitempty"`                            // 标准答案 (不可返回给学生)
	SortOrder     int32                  `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`    // 排序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionItem) Reset() {
	*x = QuestionItem{}
	mi := &file_proctor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionItem) ProtoMessage() {}

func (x *QuestionItem) ProtoReflect() protoreflect.Message {
	mi := &file_proctor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionItem.ProtoReflect.Descriptor instead.
func (*QuestionItem) Descriptor() ([]byte, []int) {
	return file_proctor_proto_rawDescGZIP(), []int{0}
}

func (x *QuestionItem) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *QuestionItem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *QuestionItem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QuestionItem) GetStem() string {
	if x != nil {
		return x.Stem
	}
	return ""
}

func (x *QuestionItem) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *QuestionItem) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QuestionItem) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

// ExamPaper 试卷快照，Java 写入 Redis exam:{examId}:paper。
type ExamPaper struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExamId         int64                  `protobuf:"varint,1,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	CourseId       int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	TotalScore     int32                  `protobuf:"varint,4,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	DurationMins   int32                  `protobuf:"varint,5,opt,name=duration_mins,json=durationMins,proto3" json:"duration_mins,omitempty"`
	PassScore      int32                  `protobuf:"varint,6,opt,name=pass_score,json=passScore,proto3" json:"pass_score,omitempty"`
	ValidStartTime int64                  `protobuf:"varint,7,opt,name=valid_start_time,json=validStartTime,proto3" json:"valid_start_time,omitempty"` // Unix timestamp (秒)
	ValidEndTime   int64                  `protobuf:"varint,8,opt,name=valid_end_time,json=validEndTime,proto3" json:"valid_end_time,omitempty"`       // Unix timestamp (秒)
	Questions      []*QuestionItem        `protobuf:"bytes,9,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExamPaper) Reset() {
	*x = ExamPaper{}
	mi := &file_proctor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExamPaper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamPaper) ProtoMessage() {}

func (x *ExamPaper) ProtoReflect() protoreflect.Message {
	mi := &file_proctor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamPaper.ProtoReflect.Descriptor instead.
func (*ExamPaper) Descriptor() ([]byte, []int) {
	return file_proctor_proto_rawDescGZIP(), []int{1}
}

func (x *ExamPaper) GetExamId() int64 {
	if x != nil {
		return x.ExamId
	}
	return 0
}

func (x *ExamPaper) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *ExamPaper) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExamPaper) GetTotalScore() int32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *ExamPaper) GetDurationMins() int32 {
	if x != nil {
		return x.DurationMins
	}
	return 0
}

func (x *ExamPaper) GetPassScore() int32 {
	if x != nil {
		return x.PassScore
	}
	return 0
}

func (x *ExamPaper) GetValidStartTime() int64 {
	if x != nil {
		return x.ValidStartTime
	}
	return 0
}

func (x *ExamPaper) GetValidEndTime() int64 {
	if x != nil {
		return x.ValidEndTime
	}
	return 0
}

func (x *ExamPaper) GetQuestions() []*QuestionItem {
	if x != nil {
		return x.Questions
	}
	return nil
}

// ExamSession 考试会话，Go 写入 Redis exam:{examId}:session:{studentId}。
// Redis 中按字段独立存取，此为整体序列化格式。
type ExamSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      int64                  `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	StudentId     int64                  `protobuf:"varint,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	ExamId        int64                  `protobuf:"varint,3,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`    // Unix timestamp (秒)
	ExpireTime    int64                  `protobuf:"varint,5,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // Unix timestamp (秒)
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                           // 0=考试中, 1=已交卷, 2=超时强制交卷
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExamSession) Reset() {
	*x = ExamSession{}
	mi := &file_proctor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExamSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamSession) ProtoMessage() {}

func (x *ExamSession) ProtoReflect() protoreflect.Message {
	mi := &file_proctor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamSession.ProtoReflect.Descriptor instead.
func (*ExamSession) Descriptor() ([]byte, []int) {
	return file_proctor_proto_rawDescGZIP(), []int{2}
}

func (x *ExamSession) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *ExamSession) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *ExamSession) GetExamId() int64 {
	if x != nil {
		return x.ExamId
	}
	return 0
}

func (x *ExamSession) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ExamSession) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *ExamSession) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// AnswerSheet 学生的全部答题记录。
type AnswerSheet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExamId        int64                  `protobuf:"varint,1,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	StudentId     int64                  `protobuf:"varint,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	RecordId      int64                  `protobuf:"varint,3,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Answers       []*AnswerEntry         `protobuf:"bytes,4,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerSheet) Reset() {
	*x = AnswerSheet{}
	mi := &file_proctor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerSheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerSheet) ProtoMessage() {}

func (x *AnswerSheet) ProtoReflect() protoreflect.Message {
	mi := &file_proctor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerSheet.ProtoReflect.Descriptor instead.
func (*AnswerSheet) Descriptor() ([]byte, []int) {
	return file_proctor_proto_rawDescGZIP(), []int{3}
}

func (x *AnswerSheet) GetExamId() int64 {
	if x != nil {
		return x.ExamId
	}
	return 0
}

func (x *AnswerSheet) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *AnswerSheet) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *AnswerSheet) GetAnswers() []*AnswerEntry {
	if x != nil {
		return x.Answers
	}
	return nil
}

// AnswerEntry 单题作答。
type AnswerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	StudentAnswer string                 `protobuf:"bytes,2,opt,name=student_answer,json=studentAnswer,proto3" json:"student_answer,omitempty"` // 空字符串表示未作答
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerEntry) Reset() {
	*x = AnswerEntry{}
	mi := &file_proctor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerEntry) ProtoMessage() {}

func (x *AnswerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proctor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerEntry.ProtoReflect.Descriptor instead.
func (*AnswerEntry) Descriptor() ([]byte, []int) {
	return file_proctor_proto_rawDescGZIP(), []int{4}
}

func (x *AnswerEntry) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *AnswerEntry) GetStudentAnswer() string {
	if x != nil {
		return x.StudentAnswer
	}
	return ""
}

// CommitExamRequest Go 交卷时发送给 Java 的请求。
// 包含评卷所需的全部信息：学生答案 + 试卷快照。
type CommitExamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExamId        int64                  `protobuf:"varint,1,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	StudentId     int64                  `protobuf:"varint,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	RecordId      int64                  `protobuf:"varint,3,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Answers       []*AnswerEntry         `protobuf:"bytes,4,rep,name=answers,proto3" json:"answers,omitempty"`                          // 学生本次所有答案
	SubmitType    int32                  `protobuf:"varint,5,opt,name=submit_type,json=submitType,proto3" json:"submit_type,omitempty"` // 0=主动交卷, 1=超时强制交卷
	SubmitTime    int64                  `protobuf:"varint,6,opt,name=submit_time,json=submitTime,proto3" json:"submit_time,omitempty"` // Unix timestamp (秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitExamRequest) Reset() {
	*x = CommitExamRequest{}
	mi := &file_proctor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitExamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitExamRequest) ProtoMessage() {}

func (x *CommitExamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proctor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitExamRequest.ProtoReflect.Descriptor instead.
func (*CommitExamRequest) Descriptor() ([]byte, []int) {
	return file_proctor_proto_rawDescGZIP(), []int{5}
}

func (x *CommitExamRequest) GetExamId() int64 {
	if x != nil {
		return x.ExamId
	}
	return 0
}

func (x *CommitExamRequest) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *CommitExamRequest) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *CommitExamRequest) GetAnswers() []*AnswerEntry {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *CommitExamRequest) GetSubmitType() int32 {
	if x != nil {
		return x.SubmitType
	}
	return 0
}

func (x *CommitExamRequest) GetSubmitTime() int64 {
	if x != nil {
		return x.SubmitTime
	}
	return 0
}

// CommitExamResponse Java 评分完成后返回的结果。
type CommitExamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TotalScore    int32                  `protobuf:"varint,2,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"` // 总分
	ErrorCode     int32                  `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitExamResponse) Reset() {
	*x = CommitExamResponse{}
	mi := &file_proctor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitExamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitExamResponse) ProtoMessage() {}

func (x *CommitExamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proctor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitExamResponse.ProtoReflect.Descriptor instead.
func (*CommitExamResponse) Descriptor() ([]byte, []int) {
	return file_proctor_proto_rawDescGZIP(), []int{6}
}

func (x *CommitExamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitExamResponse) GetTotalScore() int32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *CommitExamResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CommitExamResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// GradingTask Redis 评分队列中的任务 (grading:pending List)。
// 当 gRPC 不可用时作为降级方案。
type GradingTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExamId        int64                  `protobuf:"varint,1,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	StudentId     int64                  `protobuf:"varint,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	RecordId      int64                  `protobuf:"varint,3,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	SubmitTime    int64                  `protobuf:"varint,4,opt,name=submit_time,json=submitTime,proto3" json:"submit_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradingTask) Reset() {
	*x = GradingTask{}
	mi := &file_proctor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradingTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradingTask) ProtoMessage() {}

func (x *GradingTask) ProtoReflect() protoreflect.Message {
	mi := &file_proctor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradingTask.ProtoReflect.Descriptor instead.
func (*GradingTask) Descriptor() ([]byte, []int) {
	return file_proctor_proto_rawDescGZIP(), []int{7}
}

func (x *GradingTask) GetExamId() int64 {
	if x != nil {
		return x.ExamId
	}
	return 0
}

func (x *GradingTask) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *GradingTask) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *GradingTask) GetSubmitTime() int64 {
	if x != nil {
		return x.SubmitTime
	}
	return 0
}

var File_proctor_proto protoreflect.FileDescriptor

const file_proctor_proto_rawDesc = "" +
	"\n" +
	"\rproctor.proto\x12\n" +
	"proctor.v1\"\xbe\x01\n" +
	"\fQuestionItem\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x12\n" +
	"\x04stem\x18\x04 \x01(\tR\x04stem\x12\x18\n" +
	"\aoptions\x18\x05 \x03(\tR\aoptions\x12\x16\n" +
	"\x06answer\x18\x06 \x01(\tR\x06answer\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05R\tsortOrder\"\xc4\x02\n" +
	"\tExamPaper\x12\x17\n" +
	"\aexam_id\x18\x01 \x01(\x03R\x06examId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1f\n" +
	"\vtotal_score\x18\x04 \x01(\x05R\n" +
	"totalScore\x12#\n" +
	"\rduration_mins\x18\x05 \x01(\x05R\fdurationMins\x12\x1d\n" +
	"\n" +
	"pass_score\x18\x06 \x01(\x05R\tpassScore\x12(\n" +
	"\x10valid_start_time\x18\a \x01(\x03R\x0evalidStartTime\x12$\n" +
	"\x0evalid_end_time\x18\b \x01(\x03R\fvalidEndTime\x126\n" +
	"\tquestions\x18\t \x03(\v2\x18.proctor.v1.QuestionItemR\tquestions\"\xba\x01\n" +
	"\vExamSession\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\x03R\brecordId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\x03R\tstudentId\x12\x17\n" +
	"\aexam_id\x18\x03 \x01(\x03R\x06examId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x1f\n" +
	"\vexpire_time\x18\x05 \x01(\x03R\n" +
	"expireTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"\x95\x01\n" +
	"\vAnswerSheet\x12\x17\n" +
	"\aexam_id\x18\x01 \x01(\x03R\x06examId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\x03R\tstudentId\x12\x1b\n" +
	"\trecord_id\x18\x03 \x01(\x03R\brecordId\x121\n" +
	"\aanswers\x18\x04 \x03(\v2\x17.proctor.v1.AnswerEntryR\aanswers\"U\n" +
	"\vAnswerEntry\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12%\n" +
	"\x0estudent_answer\x18\x02 \x01(\tR\rstudentAnswer\"\xdd\x01\n" +
	"\x11CommitExamRequest\x12\x17\n" +
	"\aexam_id\x18\x01 \x01(\x03R\x06examId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\x03R\tstudentId\x12\x1b\n" +
	"\trecord_id\x18\x03 \x01(\x03R\brecordId\x121\n" +
	"\aanswers\x18\x04 \x03(\v2\x17.proctor.v1.AnswerEntryR\aanswers\x12\x1f\n" +
	"\vsubmit_type\x18\x05 \x01(\x05R\n" +
	"submitType\x12\x1f\n" +
	"\vsubmit_time\x18\x06 \x01(\x03R\n" +
	"submitTime\"\x8b\x01\n" +
	"\x12CommitExamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vtotal_score\x18\x02 \x01(\x05R\n" +
	"totalScore\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x05R\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg\"\x83\x01\n" +
	"\vGradingTask\x12\x17\n" +
	"\aexam_id\x18\x01 \x01(\x03R\x06examId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\x03R\tstudentId\x12\x1b\n" +
	"\trecord_id\x18\x03 \x01(\x03R\brecordId\x12\x1f\n" +
	"\vsubmit_time\x18\x04 \x01(\x03R\n" +
	"submitTime2]\n" +
	"\x0eProctorService\x12K\n" +
	"\n" +
	"CommitExam\x12\x1d.proctor.v1.CommitExamRequest\x1a\x1e.proctor.v1.CommitExamResponseB8\n" +
	"(com.stss.online_testing.proto.proctor.v1P\x00Z\n" +
	"proctor/v1b\x06proto3"

var (
	file_proctor_proto_rawDescOnce sync.Once
	file_proctor_proto_rawDescData []byte
)

func file_proctor_proto_rawDescGZIP() []byte {
	file_proctor_proto_rawDescOnce.Do(func() {
		file_proctor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proctor_proto_rawDesc), len(file_proctor_proto_rawDesc)))
	})
	return file_proctor_proto_rawDescData
}

var file_proctor_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proctor_proto_goTypes = []any{
	(*QuestionItem)(nil),       // 0: proctor.v1.QuestionItem
	(*ExamPaper)(nil),          // 1: proctor.v1.ExamPaper
	(*ExamSession)(nil),        // 2: proctor.v1.ExamSession
	(*AnswerSheet)(nil),        // 3: proctor.v1.AnswerSheet
	(*AnswerEntry)(nil),        // 4: proctor.v1.AnswerEntry
	(*CommitExamRequest)(nil),  // 5: proctor.v1.CommitExamRequest
	(*CommitExamResponse)(nil), // 6: proctor.v1.CommitExamResponse
	(*GradingTask)(nil),        // 7: proctor.v1.GradingTask
}
var file_proctor_proto_depIdxs = []int32{
	0, // 0: proctor.v1.ExamPaper.questions:type_name -> proctor.v1.QuestionItem
	4, // 1: proctor.v1.AnswerSheet.answers:type_name -> proctor.v1.AnswerEntry
	4, // 2: proctor.v1.CommitExamRequest.answers:type_name -> proctor.v1.AnswerEntry
	5, // 3: proctor.v1.ProctorService.CommitExam:input_type -> proctor.v1.CommitExamRequest
	6, // 4: proctor.v1.ProctorService.CommitExam:output_type -> proctor.v1.CommitExamResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proctor_proto_init() }
func file_proctor_proto_init() {
	if File_proctor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proctor_proto_rawDesc), len(file_proctor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proctor_proto_goTypes,
		DependencyIndexes: file_proctor_proto_depIdxs,
		MessageInfos:      file_proctor_proto_msgTypes,
	}.Build()
	File_proctor_proto = out.File
	file_proctor_proto_goTypes = nil
	file_proctor_proto_depIdxs = nil
}
