// Proctor 模块 protobuf 定义
// 用于 Go Proctor 和 Java API Server 之间的数据交换和 gRPC 通信

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: proctor.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProctorService_CommitExam_FullMethodName = "/proctor.v1.ProctorService/CommitExam"
)

// ProctorServiceClient is the client API for ProctorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProctorServiceClient interface {
	// CommitExam Go Proctor 通知 Java API Server 进行评分入库。
	// Go 调用此 RPC 后，Java 从请求中获取答案直接评分，
	// 无需额外从 Redis 读取。
	CommitExam(ctx context.Context, in *CommitExamRequest, opts ...grpc.CallOption) (*CommitExamResponse, error)
}

type proctorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProctorServiceClient(cc grpc.ClientConnInterface) ProctorServiceClient {
	return &proctorServiceClient{cc}
}

func (c *proctorServiceClient) CommitExam(ctx context.Context, in *CommitExamRequest, opts ...grpc.CallOption) (*CommitExamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitExamResponse)
	err := c.cc.Invoke(ctx, ProctorService_CommitExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProctorServiceServer is the server API for ProctorService service.
// All implementations must embed UnimplementedProctorServiceServer
// for forward compatibility.
type ProctorServiceServer interface {
	// CommitExam Go Proctor 通知 Java API Server 进行评分入库。
	// Go 调用此 RPC 后，Java 从请求中获取答案直接评分，
	// 无需额外从 Redis 读取。
	CommitExam(context.Context, *CommitExamRequest) (*CommitExamResponse, error)
	mustEmbedUnimplementedProctorServiceServer()
}

// UnimplementedProctorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProctorServiceServer struct{}

func (UnimplementedProctorServiceServer) CommitExam(context.Context, *CommitExamRequest) (*CommitExamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitExam not implemented")
}
func (UnimplementedProctorServiceServer) mustEmbedUnimplementedProctorServiceServer() {}
func (UnimplementedProctorServiceServer) testEmbeddedByValue()                        {}

// UnsafeProctorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProctorServiceServer will
// result in compilation errors.
type UnsafeProctorServiceServer interface {
	mustEmbedUnimplementedProctorServiceServer()
}

func RegisterProctorServiceServer(s grpc.ServiceRegistrar, srv ProctorServiceServer) {
	// If the following call panics, it indicates UnimplementedProctorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProctorService_ServiceDesc, srv)
}

func _ProctorService_CommitExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProctorServiceServer).CommitExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProctorService_CommitExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProctorServiceServer).CommitExam(ctx, req.(*CommitExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProctorService_ServiceDesc is the grpc.ServiceDesc for ProctorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProctorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proctor.v1.ProctorService",
	HandlerType: (*ProctorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitExam",
			Handler:    _ProctorService_CommitExam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proctor.proto",
}
