server:
  port: 8080 # 提供给前端和 Go 服务的调用端口

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 这里的 localhost 是因为你的 Java 代码目前运行在宿主机(WSL)，而暴露了 3306 端口
    url: jdbc:mysql://localhost:3306/stss_testing?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Singapore
    username: root
    password: root # 需与你在 docker-compose.yml 中设置的密码保持绝对一致

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名自动映射 (如 course_id 自动映射为 courseId)
  global-config:
    db-config:
      id-type: auto # 全局设置主键自增策略
      logic-delete-field: isDeleted # 全局逻辑删除字段
      logic-delete-value: 1
      logic-not-delete-value: 0

logger:
  grpc:
    host: localhost
    port: 50061
    plaintext: true
    timeout-ms: 500
    api-service-name: apiserver-service
    proctor-service-name: proctor-controller-service
